 repos:
   - repo: https://github.com/psf/black
     rev: 23.9.1
     hooks:
       - id: black

   - repo: https://github.com/PyCQA/isort
     rev: 5.12.0
     hooks:
       - id: isort
         args: ["--profile", "black"]

   - repo: https://github.com/pre-commit/mirrors-flake8
     rev: v6.1.0
     hooks:
       - id: flake8
         stages: [push]

   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: v0.991
     hooks:
       - id: mypy
         stages: [push]

   - repo: https://github.com/PyCQA/bandit
     rev: 1.7.5
     hooks:
       - id: bandit
         stages: [push]
         args: ["-r", "."]

   - repo: local
     hooks:
       - id: pip-audit
         name: pip-audit
         entry: pip-audit --exit-code-only
         language: python
         additional_dependencies: [pip-audit]
         stages: [push]

       - id: pytest
         name: pytest
         entry: pytest --maxfail=1 --disable-warnings --cache-clear
         language: python
         additional_dependencies: [pytest]
         stages: [push]